"""
Django settings for AnimeNative project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY 环境变量未设置！请在 .env 文件中配置。")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# 生产环境安全配置
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # 强制 HTTPS
    SESSION_COOKIE_SECURE = True  # Cookie 仅通过 HTTPS 传输
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方应用
    'rest_framework',
    "corsheaders",
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # 本地应用
    'animeapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 中间件
    # 'django.contrib.sessions.middleware.SessionMiddleware',  # 纯 API 使用 JWT 可以禁用
    # 'django.middleware.common.CommonMiddleware',  # 纯 API 项目不需要
    # 'django.middleware.csrf.CsrfViewMiddleware',  # 使用 JWT 不需要 CSRF 保护
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',  # API 不需要消息框架
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',  # API 不需要防点击劫持
]

ROOT_URLCONF = 'AnimeNative.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AnimeNative.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = "animeapi.CustomUser"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 文件上传大小限制
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'animeapi.utils.pagnition.StandardResultsSetPagination',
    'PAGE_SIZE': 10,
    'EXCEPTION_HANDLER': 'animeapi.utils.api_response.custom_exception_handler',
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # 访问令牌有效期：30分钟
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),    # 刷新令牌有效期：30天
    'ROTATE_REFRESH_TOKENS': True,                   # 刷新时轮换刷新令牌（增强安全性）
    'BLACKLIST_AFTER_ROTATION': True,                # 轮换后将旧令牌加入黑名单
    'ALGORITHM': 'HS256',                            # JWT签名算法：HMAC-SHA256
    'SIGNING_KEY': SECRET_KEY,                       # 签名密钥（使用Django的SECRET_KEY）
    'AUTH_HEADER_TYPES': ('Bearer',),                # 认证头类型：Bearer Token
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',        # 认证头名称
    'USER_ID_FIELD': 'id',                           # 用户ID字段
    'USER_ID_CLAIM': 'user_id',                      # JWT中的用户ID声明
}

# Redis 基础配置（供自定义 RedisClient 和 Django 缓存共用）
REDIS_HOST = os.getenv('REDIS_HOST', '127.0.0.1').replace('http://', '').replace('https://', '').rstrip('/')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)

# 组合 Redis 连接 URL（优先使用显式 REDIS_URL，其次用上面的基础配置拼接）
REDIS_URL = os.getenv('REDIS_URL')
if not REDIS_URL:
    if REDIS_PASSWORD:
        REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1"  # 使用 db=1 作为 Django 缓存库
    else:
        REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"
# 缓存配置
# 开发环境可以使用内存缓存，生产环境使用 Redis
if DEBUG:
    # 开发环境：使用本地内存缓存（不需要 Redis）
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    # 生产环境：使用 Redis 缓存
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'animeapi',  # 缓存键前缀
            'TIMEOUT': 300,  # 默认缓存超时时间（秒）
        }
    }

# CORS 跨域配置
CORS_ALLOW_CREDENTIALS = True  # 允许携带 Cookie 和认证信息

# 开发环境：允许所有源（不推荐生产环境使用）
# CORS_ORIGIN_ALLOW_ALL = True

# 生产环境：指定允许的前端域名列表（推荐）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:9000",
    "http://127.0.0.1:9000",
    # "https://your-frontend-domain.com",  # 生产环境域名
]

# 允许的 HTTP 方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 允许浏览器访问的响应头
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# 预检请求的缓存时间（秒）
CORS_PREFLIGHT_MAX_AGE = 86400  # 24小时

# Cloudflare R2 配置
CLOUDFLARE_R2 = {
    'ACCOUNT_ID': os.getenv('CLOUDFLARE_ACCOUNT_ID'),
    'ACCESS_KEY_ID': os.getenv('CLOUDFLARE_ACCESS_KEY_ID'),
    'SECRET_ACCESS_KEY': os.getenv('CLOUDFLARE_SECRET_ACCESS_KEY'),
    'BUCKET_NAME': os.getenv('CLOUDFLARE_R2_BUCKET_NAME'),
    'ENDPOINT': os.getenv('CLOUDFLARE_R2_ENDPOINT'),
    'PUBLIC_URL': os.getenv('CLOUDFLARE_R2_PUBLIC_URL'),
    'REGION': 'auto',
}

# 文件上传配置
FILE_UPLOAD_CONFIG = {
    # 单个文件大小限制（字节）
    'MAX_FILE_SIZE': 100 * 1024 * 1024,  # 100MB
    
    # 批量上传单次数量限制
    'MAX_BATCH_COUNT': 10,  # 最多一次上传10个文件
    
    # 允许的文件类型（MIME type）
    'ALLOWED_TYPES': {
        'images': [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
            'image/bmp',
            'image/svg+xml',
        ],
        'documents': [
            'application/pdf',
            'application/msword',  # .doc
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',  # .docx
            'application/vnd.ms-excel',  # .xls
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',  # .xlsx
            'application/vnd.ms-powerpoint',  # .ppt
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',  # .pptx
            'text/plain',
            'text/csv',
        ],
        'videos': [
            'video/mp4',
            'video/mpeg',
            'video/quicktime',  # .mov
            'video/x-msvideo',  # .avi
            'video/x-flv',
        ],
        'audio': [
            'audio/mpeg',  # .mp3
            'audio/wav',
            'audio/ogg',
            'audio/mp4',  # .m4a
        ],
        'archives': [
            'application/zip',
            'application/x-rar-compressed',
            'application/x-7z-compressed',
            'application/x-tar',
            'application/gzip',
        ],
    },
    
    # 允许的文件扩展名（备用验证）
    'ALLOWED_EXTENSIONS': {
        'images': ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.svg'],
        'documents': ['.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx', '.txt', '.csv'],
        'videos': ['.mp4', '.mpeg', '.mov', '.avi', '.flv'],
        'audio': ['.mp3', '.wav', '.ogg', '.m4a'],
        'archives': ['.zip', '.rar', '.7z', '.tar', '.gz'],
    },
}

# 日志配置
LOG_DIR = BASE_DIR / 'logs'
# 注意：日志目录会在首次写入日志时自动创建，或者在部署时手动创建
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 使用轮转日志
            'filename': LOG_DIR / 'animeapi.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,  # 保留5个备份
            'formatter': 'simple',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'animeapi': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# qwen_client
DASHSCOPE_API_KEY = os.getenv('DASHSCOPE_API_KEY')
DASHSCOPE_REGION = os.getenv('DASHSCOPE_REGION', 'cn')
